name: "Epever MQTT Monitor"
version: "1.0"
slug: "epever_mqtt_addon"
description: "Моніторинг даних EPEVER через MQTT"
url: "https://github.com/ig0hn/epever_mqtt_addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
services:
  - mqtt:need
options:
  mqtt_host: "core-mosquitto"  # Це хост для вбудованого брокера в Home Assistant
  mqtt_port: 1883
  mqtt_user: "mqtt_user"        # Ваш користувач MQTT
  mqtt_password: "Albert140"    # Ваш пароль MQTT
  mqtt_topic: "home/epever-solar/epever/data"
schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: str
  mqtt_topic: str
image: "ghcr.io/ig0hn/epever_mqtt_addon-{arch}"
