# config.yaml
name: "Epever MQTT Monitor"
version: "1.0"
slug: "epever_mqtt_addon"
description: "Моніторинг даних EPEVER через MQTT"
url: "https://github.com/ig0hn/epever_mqtt_addon"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
services:
  - mqtt:need
options:
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_user: "mqtt_user"
  mqtt_password: "Albert140"
  mqtt_topic: "home/epever-solar/epever/data"
  epever_host: "192.168.0.188"
  epever_port: 502
schema:
  mqtt_host: str
  mqtt_port: port
  mqtt_user: str
  mqtt_password: str
  mqtt_topic: str
  epever_host: str
  epever_port: port
init: false